spring:
  application:
    name: xwj-service-discovery
server:
  port: 8761
eureka:
#  instance:
#    hostname: eureka-server-1
#    prefer-ip-address: true
  client:
#    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://eureka-server-2:8762/eureka/,http://eureka-server-1:8761/eureka/
      defaultZone: http://10.18.23.134:8761/eureka/
  server:
    enable-self-preservation: true
  instance:
    prefer-ip-address: true
